# This workflow is entirely based on the original work of:
# Samuele Giuli (for SciFortran project)
# It is adapted here to the DMRG case + using a local action to setup OS
#
name: CI DMRG workflow 


on: 
  push:
    branches:
      - main-ci

defaults:
  run:
    shell: bash -l {0}

jobs:
  test-DMRG:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15]

    steps:

#********* SETUP PART **********

# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

# Setup OS
      - uses: ./.github/actions
        with:
          pack-type: open

# Build SciFortran
      - id: scifor
        uses: SciFortran/checkout@main

# Build DMRG
      - name: Cloning DMRG
        run: git clone https://github.com/aamaricci/nssDMRG.git nssDMRG
      - name: Install nssDMRG
        run: |
          source ~/.scifor_config_user
          export PKG_CONFIG_PATH=~/.pkgconfig.d
          export GLOB_INC=$( pkg-config --cflags scifor )
          export GLOB_LIB=$( pkg-config --libs   scifor  | sed  "s/;/ /g"  | sed 's/\\/  /g' )
          Lattice_DMRG/bin/ci_setup_dmrg.sh

# #******** TESTING PART ********
# # Testing is now included in the install script using ctest or make test
