name: CI nssDMRG

on:
  push:
    branches: [main-ci]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15]

    steps:
      - uses: actions/checkout@v4

      - name: Install SciFortran release
        id: scifor
        uses: SciFortran/checkout@main

      - name: Configure nssDMRG
        run: cmake -S . -B build-ci -DUSE_MPI=ON -DBUILD_TESTING=OFF

      - name: Build nssDMRG
        run: cmake --build build-ci --parallel 2
